-- Bekky's Touch: public application schema snapshot, 2026-09-30 UTC.
-- No customer rows, auth users, secrets, or storage objects included.
-- Restore ONLY into a fresh Supabase project; see RECOVERY.md.
-- Managed auth/storage schemas and roles must already exist.
BEGIN;
SET LOCAL search_path = public, extensions;

-- extensions
CREATE EXTENSION IF NOT EXISTS pg_stat_statements WITH SCHEMA extensions;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA extensions;
CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA extensions;
CREATE EXTENSION IF NOT EXISTS supabase_vault WITH SCHEMA vault;

-- enum types
CREATE TYPE public.user_role AS ENUM ('customer', 'staff', 'admin');
CREATE TYPE public.order_status AS ENUM ('pending', 'processing', 'shipped', 'delivered', 'cancelled', 'refunded');
CREATE TYPE public.payment_status AS ENUM ('pending', 'completed', 'failed', 'refunded');
CREATE TYPE public.discount_type AS ENUM ('percentage', 'fixed_amount');

-- sequences
CREATE SEQUENCE public.bt_products_id_seq;
CREATE SEQUENCE public.bt_order_items_id_seq;
CREATE SEQUENCE public.newsletter_subscribers_id_seq;

-- tables
CREATE TABLE public.audit_logs (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_id uuid,
  action text NOT NULL,
  table_name text NOT NULL,
  record_id uuid,
  payload jsonb,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.bt_order_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  order_id uuid NOT NULL,
  product_id bigint NOT NULL,
  product_name text NOT NULL,
  quantity integer NOT NULL,
  unit_price numeric(10,2) NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.bt_orders (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  customer_name text NOT NULL,
  email text NOT NULL,
  phone text,
  address text NOT NULL,
  city text NOT NULL,
  postcode text NOT NULL,
  subtotal numeric(10,2) NOT NULL,
  status text DEFAULT 'new'::text NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  user_id uuid
);

CREATE TABLE public.bt_products (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name text NOT NULL,
  category text NOT NULL,
  price numeric(10,2) NOT NULL,
  shade text,
  image text,
  badge text,
  active boolean DEFAULT true NOT NULL,
  inventory integer DEFAULT 100 NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.cart_items (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  cart_id uuid NOT NULL,
  variant_id uuid NOT NULL,
  quantity integer NOT NULL
);

CREATE TABLE public.carts (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_id uuid,
  session_id text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.categories (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  name text NOT NULL,
  slug text NOT NULL,
  parent_id uuid,
  description text,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.contact_messages (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  name text NOT NULL,
  email text NOT NULL,
  phone text,
  subject text NOT NULL,
  message text NOT NULL,
  order_number text
);

CREATE TABLE public.coupons (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  code text NOT NULL,
  discount_type discount_type NOT NULL,
  discount_value numeric(10,2) NOT NULL,
  min_order_amount numeric(10,2) DEFAULT 0,
  expires_at timestamp with time zone,
  is_active boolean DEFAULT true
);

CREATE TABLE public.customer_addresses (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_id uuid NOT NULL,
  address_line1 text NOT NULL,
  address_line2 text,
  city text NOT NULL,
  state text,
  postal_code text NOT NULL,
  country text NOT NULL,
  is_default boolean DEFAULT false
);

CREATE TABLE public.inventory (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  variant_id uuid NOT NULL,
  quantity_on_hand integer DEFAULT 0,
  low_stock_threshold integer DEFAULT 5,
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.newsletter_subscribers (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  email text,
  status text DEFAULT 'subscribed'::text
);

CREATE TABLE public.notifications (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_id uuid NOT NULL,
  title text NOT NULL,
  message text NOT NULL,
  is_read boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.order_items (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  order_id uuid NOT NULL,
  variant_id uuid,
  price numeric(10,2) NOT NULL,
  quantity integer NOT NULL
);

CREATE TABLE public.orders (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_id uuid,
  order_number text NOT NULL,
  status order_status DEFAULT 'pending'::order_status,
  total_amount numeric(10,2) NOT NULL,
  discount_amount numeric(10,2) DEFAULT 0,
  shipping_address_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.payment_events (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  payment_id uuid,
  event_type text NOT NULL,
  payload jsonb,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.payments (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  order_id uuid NOT NULL,
  provider text NOT NULL,
  transaction_id text,
  amount numeric(10,2) NOT NULL,
  status payment_status DEFAULT 'pending'::payment_status,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.product_images (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  product_id uuid NOT NULL,
  variant_id uuid,
  url text NOT NULL,
  alt_text text,
  is_primary boolean DEFAULT false,
  display_order integer DEFAULT 0
);

CREATE TABLE public.product_variants (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  product_id uuid NOT NULL,
  sku text NOT NULL,
  name text NOT NULL,
  price numeric(10,2) NOT NULL,
  compare_at_price numeric(10,2),
  attributes jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.products (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  name text NOT NULL,
  slug text NOT NULL,
  description text,
  category_id uuid,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.profiles (
  id uuid NOT NULL,
  first_name text,
  last_name text,
  phone text,
  role user_role DEFAULT 'customer'::user_role,
  avatar_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.reviews (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  product_id uuid NOT NULL,
  user_id uuid NOT NULL,
  rating integer,
  comment text,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.shipping_deliveries (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  order_id uuid NOT NULL,
  carrier text NOT NULL,
  tracking_number text,
  estimated_delivery timestamp with time zone,
  shipped_at timestamp with time zone
);

CREATE TABLE public.stock_movements (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  variant_id uuid NOT NULL,
  change_quantity integer NOT NULL,
  reason text NOT NULL,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.studio_address_books (
  user_id uuid DEFAULT auth.uid() NOT NULL,
  addresses jsonb DEFAULT '[]'::jsonb NOT NULL
);

CREATE TABLE public.studio_orders (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  customer_name text NOT NULL,
  email text NOT NULL,
  phone text NOT NULL,
  address text NOT NULL,
  city text NOT NULL,
  postcode text NOT NULL,
  items jsonb NOT NULL,
  subtotal numeric(10,2) NOT NULL,
  discount numeric(10,2) NOT NULL,
  total numeric(10,2) NOT NULL,
  promo_code text,
  payment_method text DEFAULT 'offline'::text NOT NULL,
  status text DEFAULT 'pending'::text NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.studio_products (
  id integer NOT NULL,
  name text NOT NULL,
  price numeric(10,2) NOT NULL,
  active boolean DEFAULT true NOT NULL
);

CREATE TABLE public.wishlists (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_id uuid NOT NULL,
  product_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now()
);

-- constraints
ALTER TABLE public.audit_logs ADD CONSTRAINT audit_logs_pkey PRIMARY KEY (id);
ALTER TABLE public.bt_order_items ADD CONSTRAINT bt_order_items_pkey PRIMARY KEY (id);
ALTER TABLE public.bt_order_items ADD CONSTRAINT bt_order_items_quantity_check CHECK (((quantity > 0) AND (quantity <= 20)));
ALTER TABLE public.bt_order_items ADD CONSTRAINT bt_order_items_unit_price_check CHECK ((unit_price >= (0)::numeric));
ALTER TABLE public.bt_orders ADD CONSTRAINT bt_orders_pkey PRIMARY KEY (id);
ALTER TABLE public.bt_orders ADD CONSTRAINT bt_orders_subtotal_check CHECK ((subtotal >= (0)::numeric));
ALTER TABLE public.bt_products ADD CONSTRAINT bt_products_inventory_check CHECK ((inventory >= 0));
ALTER TABLE public.bt_products ADD CONSTRAINT bt_products_pkey PRIMARY KEY (id);
ALTER TABLE public.bt_products ADD CONSTRAINT bt_products_price_check CHECK ((price >= (0)::numeric));
ALTER TABLE public.cart_items ADD CONSTRAINT cart_items_cart_id_variant_id_key UNIQUE (cart_id, variant_id);
ALTER TABLE public.cart_items ADD CONSTRAINT cart_items_pkey PRIMARY KEY (id);
ALTER TABLE public.cart_items ADD CONSTRAINT cart_items_quantity_check CHECK ((quantity > 0));
ALTER TABLE public.carts ADD CONSTRAINT carts_pkey PRIMARY KEY (id);
ALTER TABLE public.categories ADD CONSTRAINT categories_pkey PRIMARY KEY (id);
ALTER TABLE public.categories ADD CONSTRAINT categories_slug_key UNIQUE (slug);
ALTER TABLE public.contact_messages ADD CONSTRAINT contact_messages_email_check CHECK (((char_length(email) >= 5) AND (char_length(email) <= 254)));
ALTER TABLE public.contact_messages ADD CONSTRAINT contact_messages_message_check CHECK (((char_length(message) >= 10) AND (char_length(message) <= 4000)));
ALTER TABLE public.contact_messages ADD CONSTRAINT contact_messages_name_check CHECK (((char_length(name) >= 2) AND (char_length(name) <= 120)));
ALTER TABLE public.contact_messages ADD CONSTRAINT contact_messages_order_number_check CHECK (((order_number IS NULL) OR (char_length(order_number) <= 80)));
ALTER TABLE public.contact_messages ADD CONSTRAINT contact_messages_phone_check CHECK (((phone IS NULL) OR (char_length(phone) <= 40)));
ALTER TABLE public.contact_messages ADD CONSTRAINT contact_messages_pkey PRIMARY KEY (id);
ALTER TABLE public.contact_messages ADD CONSTRAINT contact_messages_subject_check CHECK (((char_length(subject) >= 2) AND (char_length(subject) <= 100)));
ALTER TABLE public.coupons ADD CONSTRAINT coupons_code_key UNIQUE (code);
ALTER TABLE public.coupons ADD CONSTRAINT coupons_pkey PRIMARY KEY (id);
ALTER TABLE public.customer_addresses ADD CONSTRAINT customer_addresses_pkey PRIMARY KEY (id);
ALTER TABLE public.inventory ADD CONSTRAINT inventory_pkey PRIMARY KEY (id);
ALTER TABLE public.inventory ADD CONSTRAINT inventory_quantity_on_hand_check CHECK ((quantity_on_hand >= 0));
ALTER TABLE public.inventory ADD CONSTRAINT inventory_variant_id_key UNIQUE (variant_id);
ALTER TABLE public.newsletter_subscribers ADD CONSTRAINT newsletter_subscribers_pkey PRIMARY KEY (id);
ALTER TABLE public.notifications ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);
ALTER TABLE public.order_items ADD CONSTRAINT order_items_pkey PRIMARY KEY (id);
ALTER TABLE public.order_items ADD CONSTRAINT order_items_quantity_check CHECK ((quantity > 0));
ALTER TABLE public.orders ADD CONSTRAINT orders_order_number_key UNIQUE (order_number);
ALTER TABLE public.orders ADD CONSTRAINT orders_pkey PRIMARY KEY (id);
ALTER TABLE public.payment_events ADD CONSTRAINT payment_events_pkey PRIMARY KEY (id);
ALTER TABLE public.payments ADD CONSTRAINT payments_pkey PRIMARY KEY (id);
ALTER TABLE public.payments ADD CONSTRAINT payments_transaction_id_key UNIQUE (transaction_id);
ALTER TABLE public.product_images ADD CONSTRAINT product_images_pkey PRIMARY KEY (id);
ALTER TABLE public.product_variants ADD CONSTRAINT product_variants_pkey PRIMARY KEY (id);
ALTER TABLE public.product_variants ADD CONSTRAINT product_variants_price_check CHECK ((price >= (0)::numeric));
ALTER TABLE public.product_variants ADD CONSTRAINT product_variants_sku_key UNIQUE (sku);
ALTER TABLE public.products ADD CONSTRAINT products_pkey PRIMARY KEY (id);
ALTER TABLE public.products ADD CONSTRAINT products_slug_key UNIQUE (slug);
ALTER TABLE public.profiles ADD CONSTRAINT profiles_pkey PRIMARY KEY (id);
ALTER TABLE public.reviews ADD CONSTRAINT reviews_pkey PRIMARY KEY (id);
ALTER TABLE public.reviews ADD CONSTRAINT reviews_rating_check CHECK (((rating >= 1) AND (rating <= 5)));
ALTER TABLE public.shipping_deliveries ADD CONSTRAINT shipping_deliveries_pkey PRIMARY KEY (id);
ALTER TABLE public.stock_movements ADD CONSTRAINT stock_movements_pkey PRIMARY KEY (id);
ALTER TABLE public.studio_address_books ADD CONSTRAINT studio_address_books_addresses_check CHECK (((jsonb_typeof(addresses) = 'array'::text) AND (jsonb_array_length(addresses) <= 50)));
ALTER TABLE public.studio_address_books ADD CONSTRAINT studio_address_books_pkey PRIMARY KEY (user_id);
ALTER TABLE public.studio_orders ADD CONSTRAINT studio_orders_pkey PRIMARY KEY (id);
ALTER TABLE public.studio_products ADD CONSTRAINT studio_products_pkey PRIMARY KEY (id);
ALTER TABLE public.studio_products ADD CONSTRAINT studio_products_price_check CHECK ((price >= (0)::numeric));
ALTER TABLE public.wishlists ADD CONSTRAINT wishlists_pkey PRIMARY KEY (id);
ALTER TABLE public.wishlists ADD CONSTRAINT wishlists_user_id_product_id_key UNIQUE (user_id, product_id);
ALTER TABLE public.audit_logs ADD CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE public.bt_order_items ADD CONSTRAINT bt_order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES bt_orders(id) ON DELETE CASCADE;
ALTER TABLE public.bt_order_items ADD CONSTRAINT bt_order_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES bt_products(id);
ALTER TABLE public.bt_orders ADD CONSTRAINT bt_orders_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.cart_items ADD CONSTRAINT cart_items_cart_id_fkey FOREIGN KEY (cart_id) REFERENCES carts(id) ON DELETE CASCADE;
ALTER TABLE public.cart_items ADD CONSTRAINT cart_items_variant_id_fkey FOREIGN KEY (variant_id) REFERENCES product_variants(id) ON DELETE CASCADE;
ALTER TABLE public.carts ADD CONSTRAINT carts_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.categories ADD CONSTRAINT categories_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES categories(id) ON DELETE SET NULL;
ALTER TABLE public.customer_addresses ADD CONSTRAINT customer_addresses_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.inventory ADD CONSTRAINT inventory_variant_id_fkey FOREIGN KEY (variant_id) REFERENCES product_variants(id) ON DELETE CASCADE;
ALTER TABLE public.notifications ADD CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.order_items ADD CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE;
ALTER TABLE public.order_items ADD CONSTRAINT order_items_variant_id_fkey FOREIGN KEY (variant_id) REFERENCES product_variants(id) ON DELETE SET NULL;
ALTER TABLE public.orders ADD CONSTRAINT orders_shipping_address_id_fkey FOREIGN KEY (shipping_address_id) REFERENCES customer_addresses(id);
ALTER TABLE public.orders ADD CONSTRAINT orders_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE public.payment_events ADD CONSTRAINT payment_events_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES payments(id) ON DELETE CASCADE;
ALTER TABLE public.payments ADD CONSTRAINT payments_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE;
ALTER TABLE public.product_images ADD CONSTRAINT product_images_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
ALTER TABLE public.product_images ADD CONSTRAINT product_images_variant_id_fkey FOREIGN KEY (variant_id) REFERENCES product_variants(id) ON DELETE SET NULL;
ALTER TABLE public.product_variants ADD CONSTRAINT product_variants_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
ALTER TABLE public.products ADD CONSTRAINT products_category_id_fkey FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL;
ALTER TABLE public.profiles ADD CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.reviews ADD CONSTRAINT reviews_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
ALTER TABLE public.reviews ADD CONSTRAINT reviews_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.shipping_deliveries ADD CONSTRAINT shipping_deliveries_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE;
ALTER TABLE public.stock_movements ADD CONSTRAINT stock_movements_variant_id_fkey FOREIGN KEY (variant_id) REFERENCES product_variants(id) ON DELETE CASCADE;
ALTER TABLE public.studio_address_books ADD CONSTRAINT studio_address_books_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.wishlists ADD CONSTRAINT wishlists_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
ALTER TABLE public.wishlists ADD CONSTRAINT wishlists_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;

-- indexes
CREATE INDEX idx_cart_items_cart ON public.cart_items USING btree (cart_id);
CREATE INDEX idx_products_category ON public.products USING btree (category_id);
CREATE INDEX idx_variants_product ON public.product_variants USING btree (product_id);
CREATE INDEX idx_orders_user ON public.orders USING btree (user_id);

-- functions
CREATE OR REPLACE FUNCTION public.create_bt_order(order_data jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  new_order_id uuid;
  calculated_total numeric(10,2);
begin
  if nullif(trim(order_data->>'customer_name'), '') is null
     or nullif(trim(order_data->>'email'), '') is null
     or nullif(trim(order_data->>'address'), '') is null
     or nullif(trim(order_data->>'city'), '') is null
     or nullif(trim(order_data->>'postcode'), '') is null then
    raise exception 'Required customer information is missing';
  end if;

  if jsonb_typeof(order_data->'items') <> 'array'
     or jsonb_array_length(order_data->'items') = 0 then
    raise exception 'The order must contain at least one item';
  end if;

  select coalesce(sum(p.price * requested.quantity), 0)
  into calculated_total
  from (
    select
      (item->>'product_id')::bigint as product_id,
      (item->>'quantity')::integer as quantity
    from jsonb_array_elements(order_data->'items') item
  ) requested
  join public.bt_products p
    on p.id = requested.product_id
   and p.active = true
  where requested.quantity between 1 and 20;

  if calculated_total <= 0 then
    raise exception 'No valid products were supplied';
  end if;

  insert into public.bt_orders
    (customer_name, email, phone, address, city, postcode, subtotal)
  values
    (
      trim(order_data->>'customer_name'),
      lower(trim(order_data->>'email')),
      nullif(trim(order_data->>'phone'), ''),
      trim(order_data->>'address'),
      trim(order_data->>'city'),
      upper(trim(order_data->>'postcode')),
      calculated_total
    )
  returning id into new_order_id;

  insert into public.bt_order_items
    (order_id, product_id, product_name, quantity, unit_price)
  select
    new_order_id,
    p.id,
    p.name,
    requested.quantity,
    p.price
  from (
    select
      (item->>'product_id')::bigint as product_id,
      (item->>'quantity')::integer as quantity
    from jsonb_array_elements(order_data->'items') item
  ) requested
  join public.bt_products p
    on p.id = requested.product_id
   and p.active = true
  where requested.quantity between 1 and 20;

  return jsonb_build_object(
    'order_id', new_order_id,
    'subtotal', calculated_total,
    'status', 'received'
  );
end;
$function$

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'pg_catalog', 'public'
AS $function$
BEGIN
  INSERT INTO public.profiles (id, first_name, last_name)
  VALUES (
    new.id,
    new.raw_user_meta_data->>'first_name',
    new.raw_user_meta_data->>'last_name'
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$function$


-- triggers
CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION handle_new_user();

-- row security
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_variants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock_movements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.carts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cart_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shipping_deliveries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wishlists ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customer_addresses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.coupons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payment_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bt_products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contact_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bt_order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.newsletter_subscribers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bt_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.studio_products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.studio_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.studio_address_books ENABLE ROW LEVEL SECURITY;

-- policies
CREATE POLICY "Allow public read categories" ON public.categories AS PERMISSIVE FOR SELECT TO PUBLIC USING (true);
CREATE POLICY "Allow public read product images" ON public.product_images AS PERMISSIVE FOR SELECT TO PUBLIC USING (true);
CREATE POLICY "Allow public read reviews" ON public.reviews AS PERMISSIVE FOR SELECT TO PUBLIC USING (true);
CREATE POLICY "Allow individual wishlist access" ON public.wishlists AS PERMISSIVE FOR ALL TO PUBLIC USING ((auth.uid() = user_id));
CREATE POLICY "Allow individual address access" ON public.customer_addresses AS PERMISSIVE FOR ALL TO PUBLIC USING ((auth.uid() = user_id));
CREATE POLICY "Allow public read coupons" ON public.coupons AS PERMISSIVE FOR SELECT TO PUBLIC USING (true);
CREATE POLICY "Allow read access to payment events" ON public.payment_events AS PERMISSIVE FOR SELECT TO PUBLIC USING (true);
CREATE POLICY "Public can view active products" ON public.bt_products AS PERMISSIVE FOR SELECT TO anon, authenticated USING ((active = true));
CREATE POLICY "Visitors can submit contact enquiries" ON public.contact_messages AS PERMISSIVE FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "Allow newsletter signups" ON public.newsletter_subscribers AS PERMISSIVE FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "Allow public order placement" ON public.bt_orders AS PERMISSIVE FOR INSERT TO PUBLIC WITH CHECK (true);
CREATE POLICY "Studio product browse" ON public.studio_products AS PERMISSIVE FOR SELECT TO anon, authenticated USING (active);
CREATE POLICY "Customers create own address book" ON public.studio_address_books AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((( SELECT auth.uid() AS uid) = user_id));
CREATE POLICY "Customers read own address book" ON public.studio_address_books AS PERMISSIVE FOR SELECT TO authenticated USING ((( SELECT auth.uid() AS uid) = user_id));
CREATE POLICY "Customers update own address book" ON public.studio_address_books AS PERMISSIVE FOR UPDATE TO authenticated USING ((( SELECT auth.uid() AS uid) = user_id)) WITH CHECK ((( SELECT auth.uid() AS uid) = user_id));

-- table grants
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM PUBLIC, anon, authenticated;
GRANT TRUNCATE ON TABLE public.products TO anon;
GRANT REFERENCES ON TABLE public.products TO anon;
GRANT TRIGGER ON TABLE public.products TO anon;
GRANT TRUNCATE ON TABLE public.products TO authenticated;
GRANT REFERENCES ON TABLE public.products TO authenticated;
GRANT TRIGGER ON TABLE public.products TO authenticated;
GRANT TRUNCATE ON TABLE public.products TO service_role;
GRANT REFERENCES ON TABLE public.products TO service_role;
GRANT TRIGGER ON TABLE public.products TO service_role;
GRANT TRUNCATE ON TABLE public.product_variants TO anon;
GRANT REFERENCES ON TABLE public.product_variants TO anon;
GRANT TRIGGER ON TABLE public.product_variants TO anon;
GRANT TRUNCATE ON TABLE public.product_variants TO authenticated;
GRANT REFERENCES ON TABLE public.product_variants TO authenticated;
GRANT TRIGGER ON TABLE public.product_variants TO authenticated;
GRANT TRUNCATE ON TABLE public.product_variants TO service_role;
GRANT REFERENCES ON TABLE public.product_variants TO service_role;
GRANT TRIGGER ON TABLE public.product_variants TO service_role;
GRANT TRUNCATE ON TABLE public.inventory TO anon;
GRANT REFERENCES ON TABLE public.inventory TO anon;
GRANT TRIGGER ON TABLE public.inventory TO anon;
GRANT TRUNCATE ON TABLE public.inventory TO authenticated;
GRANT REFERENCES ON TABLE public.inventory TO authenticated;
GRANT TRIGGER ON TABLE public.inventory TO authenticated;
GRANT TRUNCATE ON TABLE public.inventory TO service_role;
GRANT REFERENCES ON TABLE public.inventory TO service_role;
GRANT TRIGGER ON TABLE public.inventory TO service_role;
GRANT TRUNCATE ON TABLE public.stock_movements TO anon;
GRANT REFERENCES ON TABLE public.stock_movements TO anon;
GRANT TRIGGER ON TABLE public.stock_movements TO anon;
GRANT TRUNCATE ON TABLE public.stock_movements TO authenticated;
GRANT REFERENCES ON TABLE public.stock_movements TO authenticated;
GRANT TRIGGER ON TABLE public.stock_movements TO authenticated;
GRANT TRUNCATE ON TABLE public.stock_movements TO service_role;
GRANT REFERENCES ON TABLE public.stock_movements TO service_role;
GRANT TRIGGER ON TABLE public.stock_movements TO service_role;
GRANT TRUNCATE ON TABLE public.carts TO anon;
GRANT REFERENCES ON TABLE public.carts TO anon;
GRANT TRIGGER ON TABLE public.carts TO anon;
GRANT TRUNCATE ON TABLE public.carts TO authenticated;
GRANT REFERENCES ON TABLE public.carts TO authenticated;
GRANT TRIGGER ON TABLE public.carts TO authenticated;
GRANT TRUNCATE ON TABLE public.carts TO service_role;
GRANT REFERENCES ON TABLE public.carts TO service_role;
GRANT TRIGGER ON TABLE public.carts TO service_role;
GRANT TRUNCATE ON TABLE public.cart_items TO anon;
GRANT REFERENCES ON TABLE public.cart_items TO anon;
GRANT TRIGGER ON TABLE public.cart_items TO anon;
GRANT TRUNCATE ON TABLE public.cart_items TO authenticated;
GRANT REFERENCES ON TABLE public.cart_items TO authenticated;
GRANT TRIGGER ON TABLE public.cart_items TO authenticated;
GRANT TRUNCATE ON TABLE public.cart_items TO service_role;
GRANT REFERENCES ON TABLE public.cart_items TO service_role;
GRANT TRIGGER ON TABLE public.cart_items TO service_role;
GRANT TRUNCATE ON TABLE public.orders TO anon;
GRANT REFERENCES ON TABLE public.orders TO anon;
GRANT TRIGGER ON TABLE public.orders TO anon;
GRANT TRUNCATE ON TABLE public.orders TO authenticated;
GRANT REFERENCES ON TABLE public.orders TO authenticated;
GRANT TRIGGER ON TABLE public.orders TO authenticated;
GRANT TRUNCATE ON TABLE public.orders TO service_role;
GRANT REFERENCES ON TABLE public.orders TO service_role;
GRANT TRIGGER ON TABLE public.orders TO service_role;
GRANT TRUNCATE ON TABLE public.order_items TO anon;
GRANT REFERENCES ON TABLE public.order_items TO anon;
GRANT TRIGGER ON TABLE public.order_items TO anon;
GRANT TRUNCATE ON TABLE public.order_items TO authenticated;
GRANT REFERENCES ON TABLE public.order_items TO authenticated;
GRANT TRIGGER ON TABLE public.order_items TO authenticated;
GRANT TRUNCATE ON TABLE public.order_items TO service_role;
GRANT REFERENCES ON TABLE public.order_items TO service_role;
GRANT TRIGGER ON TABLE public.order_items TO service_role;
GRANT TRUNCATE ON TABLE public.payments TO anon;
GRANT REFERENCES ON TABLE public.payments TO anon;
GRANT TRIGGER ON TABLE public.payments TO anon;
GRANT TRUNCATE ON TABLE public.payments TO authenticated;
GRANT REFERENCES ON TABLE public.payments TO authenticated;
GRANT TRIGGER ON TABLE public.payments TO authenticated;
GRANT TRUNCATE ON TABLE public.payments TO service_role;
GRANT REFERENCES ON TABLE public.payments TO service_role;
GRANT TRIGGER ON TABLE public.payments TO service_role;
GRANT TRUNCATE ON TABLE public.shipping_deliveries TO anon;
GRANT REFERENCES ON TABLE public.shipping_deliveries TO anon;
GRANT TRIGGER ON TABLE public.shipping_deliveries TO anon;
GRANT TRUNCATE ON TABLE public.shipping_deliveries TO authenticated;
GRANT REFERENCES ON TABLE public.shipping_deliveries TO authenticated;
GRANT TRIGGER ON TABLE public.shipping_deliveries TO authenticated;
GRANT TRUNCATE ON TABLE public.shipping_deliveries TO service_role;
GRANT REFERENCES ON TABLE public.shipping_deliveries TO service_role;
GRANT TRIGGER ON TABLE public.shipping_deliveries TO service_role;
GRANT TRUNCATE ON TABLE public.notifications TO anon;
GRANT REFERENCES ON TABLE public.notifications TO anon;
GRANT TRIGGER ON TABLE public.notifications TO anon;
GRANT TRUNCATE ON TABLE public.notifications TO authenticated;
GRANT REFERENCES ON TABLE public.notifications TO authenticated;
GRANT TRIGGER ON TABLE public.notifications TO authenticated;
GRANT TRUNCATE ON TABLE public.notifications TO service_role;
GRANT REFERENCES ON TABLE public.notifications TO service_role;
GRANT TRIGGER ON TABLE public.notifications TO service_role;
GRANT TRUNCATE ON TABLE public.audit_logs TO anon;
GRANT REFERENCES ON TABLE public.audit_logs TO anon;
GRANT TRIGGER ON TABLE public.audit_logs TO anon;
GRANT TRUNCATE ON TABLE public.audit_logs TO authenticated;
GRANT REFERENCES ON TABLE public.audit_logs TO authenticated;
GRANT TRIGGER ON TABLE public.audit_logs TO authenticated;
GRANT TRUNCATE ON TABLE public.audit_logs TO service_role;
GRANT REFERENCES ON TABLE public.audit_logs TO service_role;
GRANT TRIGGER ON TABLE public.audit_logs TO service_role;
GRANT TRUNCATE ON TABLE public.profiles TO anon;
GRANT REFERENCES ON TABLE public.profiles TO anon;
GRANT TRIGGER ON TABLE public.profiles TO anon;
GRANT TRUNCATE ON TABLE public.profiles TO authenticated;
GRANT REFERENCES ON TABLE public.profiles TO authenticated;
GRANT TRIGGER ON TABLE public.profiles TO authenticated;
GRANT TRUNCATE ON TABLE public.profiles TO service_role;
GRANT REFERENCES ON TABLE public.profiles TO service_role;
GRANT TRIGGER ON TABLE public.profiles TO service_role;
GRANT TRUNCATE ON TABLE public.categories TO anon;
GRANT REFERENCES ON TABLE public.categories TO anon;
GRANT TRIGGER ON TABLE public.categories TO anon;
GRANT TRUNCATE ON TABLE public.categories TO authenticated;
GRANT REFERENCES ON TABLE public.categories TO authenticated;
GRANT TRIGGER ON TABLE public.categories TO authenticated;
GRANT TRUNCATE ON TABLE public.categories TO service_role;
GRANT REFERENCES ON TABLE public.categories TO service_role;
GRANT TRIGGER ON TABLE public.categories TO service_role;
GRANT TRUNCATE ON TABLE public.product_images TO anon;
GRANT REFERENCES ON TABLE public.product_images TO anon;
GRANT TRIGGER ON TABLE public.product_images TO anon;
GRANT TRUNCATE ON TABLE public.product_images TO authenticated;
GRANT REFERENCES ON TABLE public.product_images TO authenticated;
GRANT TRIGGER ON TABLE public.product_images TO authenticated;
GRANT TRUNCATE ON TABLE public.product_images TO service_role;
GRANT REFERENCES ON TABLE public.product_images TO service_role;
GRANT TRIGGER ON TABLE public.product_images TO service_role;
GRANT TRUNCATE ON TABLE public.reviews TO anon;
GRANT REFERENCES ON TABLE public.reviews TO anon;
GRANT TRIGGER ON TABLE public.reviews TO anon;
GRANT TRUNCATE ON TABLE public.reviews TO authenticated;
GRANT REFERENCES ON TABLE public.reviews TO authenticated;
GRANT TRIGGER ON TABLE public.reviews TO authenticated;
GRANT TRUNCATE ON TABLE public.reviews TO service_role;
GRANT REFERENCES ON TABLE public.reviews TO service_role;
GRANT TRIGGER ON TABLE public.reviews TO service_role;
GRANT TRUNCATE ON TABLE public.wishlists TO anon;
GRANT REFERENCES ON TABLE public.wishlists TO anon;
GRANT TRIGGER ON TABLE public.wishlists TO anon;
GRANT TRUNCATE ON TABLE public.wishlists TO authenticated;
GRANT REFERENCES ON TABLE public.wishlists TO authenticated;
GRANT TRIGGER ON TABLE public.wishlists TO authenticated;
GRANT TRUNCATE ON TABLE public.wishlists TO service_role;
GRANT REFERENCES ON TABLE public.wishlists TO service_role;
GRANT TRIGGER ON TABLE public.wishlists TO service_role;
GRANT TRUNCATE ON TABLE public.customer_addresses TO anon;
GRANT REFERENCES ON TABLE public.customer_addresses TO anon;
GRANT TRIGGER ON TABLE public.customer_addresses TO anon;
GRANT TRUNCATE ON TABLE public.customer_addresses TO authenticated;
GRANT REFERENCES ON TABLE public.customer_addresses TO authenticated;
GRANT TRIGGER ON TABLE public.customer_addresses TO authenticated;
GRANT TRUNCATE ON TABLE public.customer_addresses TO service_role;
GRANT REFERENCES ON TABLE public.customer_addresses TO service_role;
GRANT TRIGGER ON TABLE public.customer_addresses TO service_role;
GRANT TRUNCATE ON TABLE public.coupons TO anon;
GRANT REFERENCES ON TABLE public.coupons TO anon;
GRANT TRIGGER ON TABLE public.coupons TO anon;
GRANT TRUNCATE ON TABLE public.coupons TO authenticated;
GRANT REFERENCES ON TABLE public.coupons TO authenticated;
GRANT TRIGGER ON TABLE public.coupons TO authenticated;
GRANT TRUNCATE ON TABLE public.coupons TO service_role;
GRANT REFERENCES ON TABLE public.coupons TO service_role;
GRANT TRIGGER ON TABLE public.coupons TO service_role;
GRANT TRUNCATE ON TABLE public.payment_events TO anon;
GRANT REFERENCES ON TABLE public.payment_events TO anon;
GRANT TRIGGER ON TABLE public.payment_events TO anon;
GRANT TRUNCATE ON TABLE public.payment_events TO authenticated;
GRANT REFERENCES ON TABLE public.payment_events TO authenticated;
GRANT TRIGGER ON TABLE public.payment_events TO authenticated;
GRANT TRUNCATE ON TABLE public.payment_events TO service_role;
GRANT REFERENCES ON TABLE public.payment_events TO service_role;
GRANT TRIGGER ON TABLE public.payment_events TO service_role;
GRANT SELECT ON TABLE public.bt_products TO anon;
GRANT TRUNCATE ON TABLE public.bt_products TO anon;
GRANT REFERENCES ON TABLE public.bt_products TO anon;
GRANT TRIGGER ON TABLE public.bt_products TO anon;
GRANT SELECT ON TABLE public.bt_products TO authenticated;
GRANT TRUNCATE ON TABLE public.bt_products TO authenticated;
GRANT REFERENCES ON TABLE public.bt_products TO authenticated;
GRANT TRIGGER ON TABLE public.bt_products TO authenticated;
GRANT TRUNCATE ON TABLE public.bt_products TO service_role;
GRANT REFERENCES ON TABLE public.bt_products TO service_role;
GRANT TRIGGER ON TABLE public.bt_products TO service_role;
GRANT INSERT ON TABLE public.contact_messages TO service_role;
GRANT SELECT ON TABLE public.contact_messages TO service_role;
GRANT TRUNCATE ON TABLE public.contact_messages TO service_role;
GRANT REFERENCES ON TABLE public.contact_messages TO service_role;
GRANT TRIGGER ON TABLE public.contact_messages TO service_role;
GRANT INSERT ON TABLE public.contact_messages TO anon;
GRANT INSERT ON TABLE public.contact_messages TO authenticated;
GRANT TRUNCATE ON TABLE public.bt_order_items TO service_role;
GRANT REFERENCES ON TABLE public.bt_order_items TO service_role;
GRANT TRIGGER ON TABLE public.bt_order_items TO service_role;
GRANT INSERT ON TABLE public.newsletter_subscribers TO anon;
GRANT SELECT ON TABLE public.newsletter_subscribers TO anon;
GRANT UPDATE ON TABLE public.newsletter_subscribers TO anon;
GRANT DELETE ON TABLE public.newsletter_subscribers TO anon;
GRANT TRUNCATE ON TABLE public.newsletter_subscribers TO anon;
GRANT REFERENCES ON TABLE public.newsletter_subscribers TO anon;
GRANT TRIGGER ON TABLE public.newsletter_subscribers TO anon;
GRANT INSERT ON TABLE public.newsletter_subscribers TO authenticated;
GRANT SELECT ON TABLE public.newsletter_subscribers TO authenticated;
GRANT UPDATE ON TABLE public.newsletter_subscribers TO authenticated;
GRANT DELETE ON TABLE public.newsletter_subscribers TO authenticated;
GRANT TRUNCATE ON TABLE public.newsletter_subscribers TO authenticated;
GRANT REFERENCES ON TABLE public.newsletter_subscribers TO authenticated;
GRANT TRIGGER ON TABLE public.newsletter_subscribers TO authenticated;
GRANT INSERT ON TABLE public.newsletter_subscribers TO service_role;
GRANT SELECT ON TABLE public.newsletter_subscribers TO service_role;
GRANT UPDATE ON TABLE public.newsletter_subscribers TO service_role;
GRANT DELETE ON TABLE public.newsletter_subscribers TO service_role;
GRANT TRUNCATE ON TABLE public.newsletter_subscribers TO service_role;
GRANT REFERENCES ON TABLE public.newsletter_subscribers TO service_role;
GRANT TRIGGER ON TABLE public.newsletter_subscribers TO service_role;
GRANT TRUNCATE ON TABLE public.bt_orders TO service_role;
GRANT REFERENCES ON TABLE public.bt_orders TO service_role;
GRANT TRIGGER ON TABLE public.bt_orders TO service_role;
GRANT SELECT ON TABLE public.studio_products TO anon;
GRANT TRUNCATE ON TABLE public.studio_products TO anon;
GRANT REFERENCES ON TABLE public.studio_products TO anon;
GRANT TRIGGER ON TABLE public.studio_products TO anon;
GRANT SELECT ON TABLE public.studio_products TO authenticated;
GRANT TRUNCATE ON TABLE public.studio_products TO authenticated;
GRANT REFERENCES ON TABLE public.studio_products TO authenticated;
GRANT TRIGGER ON TABLE public.studio_products TO authenticated;
GRANT SELECT ON TABLE public.studio_products TO service_role;
GRANT TRUNCATE ON TABLE public.studio_products TO service_role;
GRANT REFERENCES ON TABLE public.studio_products TO service_role;
GRANT TRIGGER ON TABLE public.studio_products TO service_role;
GRANT INSERT ON TABLE public.studio_orders TO service_role;
GRANT SELECT ON TABLE public.studio_orders TO service_role;
GRANT TRUNCATE ON TABLE public.studio_orders TO service_role;
GRANT REFERENCES ON TABLE public.studio_orders TO service_role;
GRANT TRIGGER ON TABLE public.studio_orders TO service_role;
GRANT INSERT ON TABLE public.studio_address_books TO authenticated;
GRANT SELECT ON TABLE public.studio_address_books TO authenticated;
GRANT UPDATE ON TABLE public.studio_address_books TO authenticated;
GRANT TRUNCATE ON TABLE public.studio_address_books TO authenticated;
GRANT REFERENCES ON TABLE public.studio_address_books TO authenticated;
GRANT TRIGGER ON TABLE public.studio_address_books TO authenticated;
GRANT TRUNCATE ON TABLE public.studio_address_books TO service_role;
GRANT REFERENCES ON TABLE public.studio_address_books TO service_role;
GRANT TRIGGER ON TABLE public.studio_address_books TO service_role;

-- function permissions
REVOKE ALL ON FUNCTION create_bt_order(jsonb) FROM PUBLIC, anon, authenticated;

REVOKE ALL ON FUNCTION handle_new_user() FROM PUBLIC, anon, authenticated;


-- Bucket definitions only: uploaded objects require a separate backup.
INSERT INTO storage.buckets(id,name,public) VALUES ('product-images','product-images',true),('user-avatars','user-avatars',true) ON CONFLICT (id) DO NOTHING;
COMMIT;
